### ISSUE TITLE
[Enhancement] Distribute on extensions.libreoffice.org

### ISSUE THREAD

**Issue by Asten-Valentinus** [balisujohn/localwriter#14]
Distributing localwriter on extensions.libreoffice.org (the official place to get LibreOffice extensions) will allow more people to discover this extension, as well as allow support for LibreOffice's extension update functionality.

You can see the official instructions for doing this [here.](https://extensions.libreoffice.org/en/home/using-this-site-as-an-extension-maintainer/)

_Thanks again for this amazing extension!_

**Comment by balisujohn** [comment]
Already there :^)

https://extensions.libreoffice.org/en/extensions/show/99224

**Comment by Asten-Valentinus** [comment]
Nice, I hadn't seen it there before!
