### ISSUE TITLE
Localwriter menu not showing

### ISSUE THREAD

**Issue by arsaboo** [balisujohn/localwriter#2]
I just added the extension (v.0.0.2) to LibreOffice but don't see any additional Localwriter menu. 

![image](https://github.com/user-attachments/assets/12a74bd0-491e-413c-b30e-4e199cad81b2)

![image](https://github.com/user-attachments/assets/c2d71590-e20b-4fae-ab1b-00674c03859f)

Is there anything else required?

**Comment by arsaboo** [comment]
Ok...so I changed the toolbar to standard view and now it works.

**Comment by viba1** [comment]
Hi,
Same problem here, localwriter menu is displayed in the standard menu but clicking on "settings" but **nothing happens**.
This makes the extension's usage impossible, which is very unfortunate. 

Some improvement suggestions:
1.    Fix the settings menu display bug.
2.    Make parameters directly accessible from the Extensions > Options menu in LibreOffice Writer. This would allow configuration even if the standard menu bar is not displayed.

These modifications would make the extension more robust and easier to use for all users, regardless of their LibreOffice configuration.

![Capture d’écran du 2024-11-24 14-15-16](https://github.com/user-attachments/assets/6f90dc85-36ba-453d-bf58-1ccbebe04a50)
