### ISSUE TITLE
Doesn't work in table

### ISSUE THREAD

**Issue by athyfr** [balisujohn/localwriter#4]
When I try to use this on text that is in a table, it doesn't seem to do anything.

**Comment by balisujohn** [comment]
I was able to reproduce that behavior; I'll look into it.

**Comment by balisujohn** [comment]
Should be fixed with the new release! Let me know if it works ok for you. 

https://github.com/balisujohn/localwriter/releases/tag/v0.0.4

If you find this software useful, I'd love to hear about how you use it. Such information makes this project stronger.

**Comment by balisujohn** [comment]
Thanks for the information, and feel free to submit feature requests going forward.
